App\Domain\Post\Post:
    properties:
        content:
            - NotBlank: ~
        link:
            - NotBlank: ~
            - Url:
                requireTld: true
        author:
            - NotBlank: ~

